name: Deploy to Heroku

on:
  push:
    branches: [main, master]
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Build TypeScript
        run: npm run build

      - name: Setup Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Set buildpack (ignore error if already set)
          heroku buildpacks:set heroku/nodejs -a ${{ secrets.HEROKU_APP_NAME }} || echo "Buildpack already set"
          
          # Add Heroku remote and deploy
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git || true
          git push heroku HEAD:main -f
